name: flappy_bird
description: Flappy Bird in Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1  # For playing sound effects
  shared_preferences: ^2.0.11  # For storing high scores locally
  cupertino_icons: ^1.0.6 
  path_provider: ^2.0.11 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Recommended linting rules for good coding practices

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Directory for sprite images
    - assets/sounds/   # Directory for sound files

